source_path: "/data3/zhangshuai/SC-2DGSv2/data/bouncingballs"
model_path: "/data3/zhangshuai/SC-2DGSv2/outputs/bouncingballs"

deform_type: "node"
white_background: True
eval: True
is_blender: True
gt_alpha_mask_as_scene_mask: True
local_frame: True
resolution: 1

