source_path: "/data3/zhangshuai/SC-2DGSv2/data/jumpingjacks"
model_path: "/data3/zhangshuai/SC-2DGSv2/outputs/jumpingjacks_0731_node"

deform_type: "node"
white_background: True
eval: True
is_blender: True
gt_alpha_mask_as_scene_mask: True
local_frame: True
hyper_dim: 8
node_num: 1024
resolution: 1

